# Generated by Django 5.0.3 on 2024-03-15 00:06

import django.db.models.deletion
import restaurant.models.restaurant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=250, upload_to='uploads/dish/%Y/%m/%d/', validators=[restaurant.models.restaurant.file_size_validator])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='restaurant.dish')),
            ],
        ),
    ]
